#pragma once

const enum ErrorCode {
	FILE_EXTENSION_ERROR,
	FILE_OPEN_FLASE,
	CODE_ERROR,
	DATA_ERROR,
	MEMBER_MISSING,
	LOAD_SCENE_DATA_ERROR,
	SCENE_ATTRIBUTE_MISSING,
	LOAD_NODE_DATA_ERROR,
	NODE_ATTRIBUTE_MISSING,
	LOAD_TEXTURE_DATA_ERROR,
	TEXTRUE_ATTRIBUTE_MISSING,
	LOAD_MATERIAL_DATA_ERROR,
	MATERIAL_ATTRIBUTE_MISSING,
	LOAD_MESH_DATA_ERROR,
	MESH_ATTRIBUTE_MISSING,
	OBJECT_ATTRIBUTE_MISSING,
	OBJECT_PART_ATTRIBUTE_MISSING,
	SPINNER_ATTRIBUTE_MISSING,
	ANIMATOR_ATTRIBUTE_MISSING,
	DUMMY_ATTRIBUTE_MISSING,
	OPEN_FILE_FASLE,
	WRITE_FILE_ERROR,
};

