#pragma once

const enum ErrorCode {
	FILE_EXTENSION_ERROR,
	FILE_OPEN_FLASE,
	CODE_ERROR,
	LOAD_SCENE_DATA_ERROR,
	LOAD_NODE_DATA_ERROR,
	NODE_ATTRIBUTE_MISSING,
	LOAD_TEXTURE_DATA_ERROR,
	TEXTRUE_ATTRIBUTE_MISSING,
	LOAD_MESH_DATA_ERROR,
	MESH_ATTRIBUTE_MISSING,
	OPEN_FILE_FASLE,
	WRITE_FILE_ERROR,
};
